spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.auto_quote_keyword: true
  application:
    name: admin3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/admin3?characterEncoding=utf8
    username: root
    password: 123456
  sql:
    init:
      encoding: utf8
      data-locations: classpath:data.sql
      mode: never
      continue-on-error: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  profiles:
    include: biz
xiaoyi:
  mcp:
    auth:
      appId: admin3-leave-app
      apiKey: admin3-leave-api-key-2026

server:
  port: 9099
  servlet:
    context-path: /admin3
